# coding: utf-8

"""
    Todolist RESTful API

    OpenAPI for Todolist RESTful API  # noqa: E501

    OpenAPI spec version: 1
    Contact: ikoafianando123@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.array_todolist import ArrayTodolist  # noqa: E501
from swagger_client.rest import ApiException


class TestArrayTodolist(unittest.TestCase):
    """ArrayTodolist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArrayTodolist(self):
        """Test ArrayTodolist"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.array_todolist.ArrayTodolist()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
