# coding: utf-8

# flake8: noqa

"""
    Todolist RESTful API

    OpenAPI for Todolist RESTful API  # noqa: E501

    OpenAPI spec version: 1
    Contact: ikoafianando123@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.todolist_api import TodolistApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.array_todolist import ArrayTodolist
from swagger_client.models.create_or_update_todolist import CreateOrUpdateTodolist
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.todolist import Todolist
