# coding: utf-8

"""
    Todolist RESTful API

    OpenAPI for Todolist RESTful API  # noqa: E501

    OpenAPI spec version: 1
    Contact: ikoafianando123@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateOrUpdateTodolist(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'priority': 'float',
        'tags': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'priority': 'priority',
        'tags': 'tags'
    }

    def __init__(self, name=None, priority=None, tags=None):  # noqa: E501
        """CreateOrUpdateTodolist - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._priority = None
        self._tags = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if priority is not None:
            self.priority = priority
        if tags is not None:
            self.tags = tags

    @property
    def name(self):
        """Gets the name of this CreateOrUpdateTodolist.  # noqa: E501


        :return: The name of this CreateOrUpdateTodolist.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateOrUpdateTodolist.


        :param name: The name of this CreateOrUpdateTodolist.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def priority(self):
        """Gets the priority of this CreateOrUpdateTodolist.  # noqa: E501


        :return: The priority of this CreateOrUpdateTodolist.  # noqa: E501
        :rtype: float
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this CreateOrUpdateTodolist.


        :param priority: The priority of this CreateOrUpdateTodolist.  # noqa: E501
        :type: float
        """

        self._priority = priority

    @property
    def tags(self):
        """Gets the tags of this CreateOrUpdateTodolist.  # noqa: E501


        :return: The tags of this CreateOrUpdateTodolist.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CreateOrUpdateTodolist.


        :param tags: The tags of this CreateOrUpdateTodolist.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateOrUpdateTodolist, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateOrUpdateTodolist):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
